# Generated by Django 2.2.4 on 2019-08-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BMI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='회원명')),
                ('height', models.FloatField(verbose_name='신장')),
                ('weight', models.FloatField(verbose_name='체중')),
                ('bmi_level', models.FloatField(blank=True, null=True, verbose_name='비만도')),
            ],
        ),
    ]
